name: Renderizar e Enviar Relatório

on:
  schedule:
    - cron: '0 12 * * *'  # Roda todo dia ao meio-dia UTC (9h no horário de Brasília)
  workflow_dispatch:  # Permite execução manual pelo GitHub Actions

jobs:
  render-relatorio:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Definir variáveis de ambiente do AWS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          TZ: ${{ secrets.TZ }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          USERNAME_RIB: ${{ secrets.USERNAME_RIB }}
          PASSWORD_RIB: ${{ secrets.PASSWORD_RIB }}
          GMAIL_AUTH: ${{ secrets.GMAIL_AUTH }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
        run: |
          echo "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" >> ~/.Renviron
          echo "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" >> ~/.Renviron
          echo "AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}" >> ~/.Renviron
          echo "TZ=${TZ}" >> ~/.Renviron
          echo "USERNAME=${USERNAME}" >> ~/.Renviron
          echo "PASSWORD=${PASSWORD}" >> ~/.Renviron
          echo "USERNAME_RIB=${USERNAME_RIB}" >> ~/.Renviron
          echo "PASSWORD_RIB=${PASSWORD_RIB}" >> ~/.Renviron
          echo "GMAIL_AUTH=${GMAIL_AUTH}" >> ~/.Renviron
          echo "SMTP_USER=${SMTP_USER}" >> ~/.Renviron
          echo "SMTP_PASS=${SMTP_PASS}" >> ~/.Renviron
          echo "$GMAIL_AUTH" > gmail_credentials.json
      - name: Construir e rodar o container Docker
        run: |
          docker build -t relatorio-render .
          docker run --rm -v $(pwd):/app relatorio-render
          
      - name: Enviar relatório para o S3
        run: |
          aws s3 cp program_conecta_campinas.pdf s3://automacao-conecta/program_conecta_campinas.pdf
