name: Run R Scripts Every Hour

on:
  schedule:
    - cron: '0 * * * *'  # Executa no início de cada hora (minuto 0)
  workflow_dispatch:  # Permite acionar o workflow manualmente

jobs:
  run-r-scripts:
    runs-on: ubuntu-latest  # Usa uma máquina virtual com Ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Faz o checkout do repositório

      - name: Set up R
        uses: r-lib/actions/setup-r@v2  # Configura o R (usa a versão mais recente)

      - name: Install system dependencies for ragg and arrow
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev libfreetype6-dev libpng-dev libtiff5-dev libfontconfig1-dev

      - name: Cache R packages
        id: r-cache
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}  # Diretório onde os pacotes R são instalados
          key: r-packages-${{ hashFiles('**/DESCRIPTION') }}  # Chave de cache baseada em arquivos do projeto
          restore-keys: |
            r-packages-  # Chave de fallback para cache

      - name: Install required R packages
        run: |
          Rscript -e 'install.packages("tidyverse")'

      - name: Definir variáveis de ambiente do AWS e outras
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          TZ: ${{ secrets.TZ }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          USERNAME_RIB: ${{ secrets.USERNAME_RIB }}
          PASSWORD_RIB: ${{ secrets.PASSWORD_RIB }}
          GMAIL_AUTH: ${{ secrets.GMAIL_AUTH }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
        run: |
          echo "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" >> ~/.Renviron
          echo "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" >> ~/.Renviron
          echo "AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}" >> ~/.Renviron
          echo "TZ=${TZ}" >> ~/.Renviron
          echo "USERNAME=${USERNAME}" >> ~/.Renviron
          echo "PASSWORD=${PASSWORD}" >> ~/.Renviron
          echo "USERNAME_RIB=${USERNAME_RIB}" >> ~/.Renviron
          echo "PASSWORD_RIB=${PASSWORD_RIB}" >> ~/.Renviron
          echo "GMAIL_AUTH=${GMAIL_AUTH}" >> ~/.Renviron
          echo "SMTP_USER=${SMTP_USER}" >> ~/.Renviron
          echo "SMTP_PASS=${SMTP_PASS}" >> ~/.Renviron
          echo "$GMAIL_AUTH" > gmail_credentials.json

      - name: Run R scripts
        run: |
          Rscript ribeirao_.R
